services:

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: agendamentoVeicularApi
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - car
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "usuario" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy  # Espera até que o serviço esteja saudável
    networks:
      - car

networks:
  car:
    driver: bridge